- Cargo.toml
- src/tcp_options.rs
This adds an `fwmark` option to `TcpOptions`, primarily for setting `SO_MARK` on the "forwarding" TCP socket in `Udp2Tcp`. This is useful in applying different routing and nftables/iptables rules to the TCP socket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/1)
> Add SO_MARK TCP option

- Cargo.toml
- src/udp2tcp.rs
`SO_MARK` needs to be set before connecting to the TCP server. This is not possible using tokio 0.2 without a temporary workaround.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/2)
> Set SO_MARK on socket before connecting

- src/bin/tcp2udp.rs
- src/tcp2udp.rs
First commit: Just extracts Tokio runtime creation to separate function. Just for cleanliness.
Second commit: Makes the `tcp2udp` binary require at least one TCP listen addr. Before now it would just panic if none was given. And also the `--help` output was worse than it is now.
This also introduces a new error type. For now we still return the opaque `Box<dyn Error>` type. That's because I did not feel like completely refactoring all errors at once. But at least this allows me to return what was previously a panic as a "real" error. `Tcp2UdpError` an be extended with more structured error variants later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/4)
> Require one tcp listen addr

- src/bin/tcp2udp.rs
- src/tcp2udp.rs
I realized a few things were actually diverging functions, never returning. But their documentation said otherwise, and their types did not hint at this either. So I tried to fix that. What do you think of this way to better signal when/how things abort (they don't)?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/6)
> Improve tcp2udp return types and documentation

- src/bin/udp2tcp.rs
- src/udp2tcp.rs
The rationale is that `TcpOptions::default()` looks better than `None` when calling the function. Our binary always had a `TcpOptions` at hand anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/7)
> Change Option<TcpOptions> to just TcpOptions

- src/bin/tcp2udp.rs
- src/forward_traffic.rs
- src/lib.rs
As you pointed out in the previous PR, more return types could make use of `Infallible`. As I started implementing that I realized a helper trait could eliminate some code paths and make some code more readable. So I added that. It has to be a public trait in order for `src/bin/tcp2udp.rs` to use it.
I also corrected/added some more documentation to code and functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/8)
> Use Infallible more extensively in return types

- tests/udp2tcp.rs
Now when we have such a shiny CI. Let's test it out!
We had an embarrassing number of tests in this crate (zero). So here comes a few. Not full coverage or anything. But it's a start! Avoiding too large PRs and getting to discuss the test design a bit before I spend too much time.
I wish `#[tokio::test]` had a timeout feature. To protect ourselves from tests that run forever. Better they give up after a few seconds and report an error. But I could not find anything about this. We can write a macro that just creates tests wrapped in `tokio::time::timeout`. But I left that out for now... Maybe worth introducing?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/10)
> Add some initial tests for the Udp2Tcp type

- Cargo.lock
- Cargo.toml
- README.md
- src/lib.rs
- src/logging.rs
- src/tcp2udp.rs
- src/udp2tcp.rs
- tcp2udp.service
Enables logging verbosely without capturing the IPs of the peers using the proxy service. To allow running the server part without storing user sensitive data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/11)
> Add possibility to redact logging via env var REDACT_LOGS

- src/bin/tcp2udp.rs
- src/bin/udp2tcp.rs
- src/lib.rs
I realized we don't have any unsafe code at the moment. And if we can avoid it we should not use it in the future neither. This crate does not really do much that would justify unsafe code right now. So I felt it was better to have this safeguard now and if we later want to introduce `unsafe` we need to justify it well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/12)
> Forbid all unsafe code

- README.md
- src/lib.rs
The documentation was not updated when we changed the API. This was missed because the `ignore` tag was used instead of `no_run`. Now the CI tests should actually catch errors in the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/14)
> Actually compile the doctest (and fix it)

- src/forward_traffic.rs
- src/udp2tcp.rs
This avoids blowing up the size of the futures, causing stack overflow on Windows in debug builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/15)
> Move all the 64k buffers for UDP datagrams to the heap

- Cargo.lock
- Cargo.toml
- src/bin/tcp2udp.rs
- src/forward_traffic.rs
- src/lib.rs
The important upgrade here is `nix = "0.23.1"` which has a more lax dependency specification in it, so it integrates better in our upstream app later.
While at it I did a full `cargo update`. At least `tokio` had a known CVE in the version we were using here.
I had to rename `into_err`. Nightly started warning about it: https://github.com/mullvad/udp-over-tcp/runs/4792292687?check_suite_focus=true#step:4:114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/17)
> Upgrade dependencies (and fix nightly warning)

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/tcp2udp.rs
- src/bin/udp2tcp.rs
- src/lib.rs
I saw that there was a new release of `env_logger`. So I figured we could upgrade. We should provide a new build of `tcp2udp` to infra rather soon anyway, so better get on the latest stuff.
I then also realized that the library depends on `env_logger`. It's not very nice of *libraries* to pull in loggers. One potential solution to this would be to put the binaries in separate crates and avoid the dependency completely in `udp-over-tcp`. But that was way more boilerplate and overhead than making it optional like this PR does. Activating the feature when building the library does absolutely nothing. Is this an OK compromise compared to the separate crates in your opinion?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Upgrade env logger and make it optional

- build-static-bins.sh
When deploying this to the infrastructure we want it statically linked. We also want logging to be turned on. So there is a hefty set of flags one must pass to get the correct results. I figured it would be way easier to build and to build in the same way every time if we add a script for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/20)
> Add a script to easily build the binaries statically linked

- tcp2udp.service
Shows how to run the service with a raised soft limit
on the number of open FDs. Since the default is pretty
often low, and the service should be able to handle
many simultaneous connections
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/23)
> Add LimitNOFILE=16384 to the example tcp2udp.service

- Cargo.toml
- src/bin/tcp2udp.rs
- src/forward_traffic.rs
- src/tcp2udp.rs
- src/tcp_options.rs
- src/udp2tcp.rs
- tcp2udp.service
This PR adds an optional read timeout for `tcp2udp`. It does not touch any socket options but simply uses `tokio::time::timeout`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/24)
> Add TCP recv timeout option

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- build-static-bins.sh
- src/tcp2udp.rs
- src/tcp_options.rs
I realize that structopt pulls in clap 2.x. And in our main repo we use clap 3.x.. So this will allow us to cut the dependency tree a bit.. Also, a library should not depend on a crate used to create CLIs...
Fixes #25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/26)
> Make structopt optional

- Cargo.lock
The CI fails due to [RUSTSEC-2022-0013](https://rustsec.org/advisories/RUSTSEC-2022-0013). This crate is only used by `env_logger` for log filtering.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/29)
> Update regex crate to 1.6

- CHANGELOG.md
- src/tcp2udp.rs
`udp-bind` defaults to `0.0.0.0` for `tcp2udp`. This means that `AF_INET` is used as the address family even if the destination is an IPv6 address. This PR fixes this by binding the socket to `::` by default if the destination is an IPv6 address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/28)
> Choose correct address family for UDP socket when `udp-bind` is not specified explicitly

- .github/workflows/ci.yml
- src/tcp2udp.rs
- src/tcp_options.rs
- src/udp2tcp.rs
This is useful for obtaining the UDP address of the `Udp2Tcp` instance before connecting to the TCP endpoint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/32)
> Add option to connect to TCP endpoint when the first UDP datagram is received

- src/tcp_options.rs
- src/udp2tcp.rs
- tests/udp2tcp.rs
Useful to have since we want to exclude the socket from the tunnel on Android.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/33)
> Add method for obtaining the raw TCP socket file descriptor

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
Preparing for a new release (`0.3.0`). But I realized that we ignore `RUSTSEC-2021-0145` and still have `atty` in our dependency tree. It was easy to get rid of however, since we only had to upgrade `env_logger`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/40)
> Upgrade env_logger to get rid of atty

- src/bin/tcp2udp.rs
- src/bin/udp2tcp.rs
A regression after the migration from `structopt` to `clap 4`: It was no longer possible to get the version of the program from the CLI interface. This adds that back. So infra can check what version they are running.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/41)
> Allow getting the crate version from the CLI

- .github/workflows/ci.yml
- Cargo.lock
Changing so CI builds with Rust 1.70 and newer only. `cargo-all-features` does not build on anything older. And MSRV tracking is a lost cause/not important anyway (completely separate discussion)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/45)
> Fix CI breakage by upgrading hermit-abi and proc-macro2

- Cargo.lock
- Cargo.toml
- src/tcp_options.rs
Just general maintenance. Bringing dependencies up to date. First commit is just `cargo update` and second commit is getting `nix` to the latest version (which slightly changes the API of `get/setsockopt`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/47)
> Upgrade dependencies

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- build-static-bins.sh
- src/statsd.rs
- src/tcp2udp.rs
- tcp2udp.service
To better monitor the health of the `tcp2udp` (WireGuard over TCP server side component) service, we should add simple error metrics to it. After discussion with @Rizzly we agreed on adding a counter that shows number of connected clients, and an error event when we fail to accept incoming TCP connections.
I added it in such a way that both the library and the binary can be compiled without statsd support. This makes the entire dependency optional. Just like we have done with `clap` and `env_logger`. This forced me to expose a dummy-layer of the metrics so the code still builds when it's not enabled, and so the metrics callsites did not become too complex (I did not want the metrics reporting to interfere a lot with the actual forwarding logic code)
- - -
This change is [<img …
> Add (optional) statsd metrics reporting

- src/statsd.rs
- src/tcp2udp.rs
- src/tcp_options.rs
- src/udp2tcp.rs
I was about to bump the version and release. Given that we have added an error variant to an enum and a field to a struct it's technically a breaking change even if the feature is off by default... At least I think it should count as that :thinking: Because even if you as a direct user of `udp-over-tcp` does not activate the feature, a transitive dependency might....
The fix for the error enum is easy, make them `#[non_exhaustive]`. I think this is a pretty good default for error enums to begin with. Because it allows adding more error cases without it being a breaking change...
But what about the `Options` struct? I figured the best might be to also make it `#[non_exhaustive]` and provide facilities for users to construct it without hitting compilation errors both if others enable the …
> Make growing types non exhaustive

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Let's release #51!
Is a breaking change both since we add fields/variants to existing public types, *and* because we mark some types as `#[non_exhaustive]`. Both of these things cause API breakage compared to version `0.3.1`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/53)
> Bump version to 0.4.0

- .github/workflows/ci.yml
- Cargo.toml
- src/forward_traffic.rs
Makes use of the really nice `split_first_chunk` introduced in Rust 1.77.
All of the changes are not strictly needed to use `split_first_chunk` but I saw some refactoring possibilities at the same time. Breaking out `split_first_datagram` to a separate function allowed me to nicely use `?`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/56)
> Use `split_first_chunk` to somewhat clean up `forward_datagrams_in_buffer`

- CHANGELOG.md
- src/lib.rs
- src/tcp_options.rs
As discussed in the office. Having errors simply be public enums with associated data makes the implementation details part of the public API. Then almost all changes to the error are breaking changes. Here I show two potential ways to implement errors so that their internals are hidden, but it's equally easy to match for a library consumer.
This is currently split into two commits, one per proposed solution. So view it per commit if you want to compare them. I personally like the second solution the best. That error implementation could fairly easily be generated by a macro. I'm sure we are not the first people to come to this conclusion, maybe there is such a macro crate on crates.io already?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Hide details of error implementation, to not make changes into breaking changes

- .github/workflows/ci.yml
- Cargo.toml
- src/forward_traffic.rs
Simplifies the code primarily. Probably allows for sliiightly more optimized code when compiling without optimizations also (?) For opt-level=3 the result is the same as before.
This split method was stabilized in Rust 1.80, released yesterday. But we don't need to support any old compilers. We are also not aiming for a release of this program/library right away. This is just a cleanup I have been wanting to do for a long time :D
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/64)
> Use <[T]>::split_at_checked instead of two separate get calls

- Cargo.lock
- Cargo.toml
futures-util 0.3.28 is yanked which is causing the CI to fail
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/67)
> Bump futures dep and run cargo update

- src/forward_traffic.rs
- src/lib.rs
Currently, the Mullvad app is forced to assume that the header is 2 bytes long: https://github.com/mullvad/mullvadvpn-app/blob/f72944e5fe88cb954a93da7bd2a868eb75c445ae/tunnel-obfuscation/src/udp2tcp.rs#L94
That's fine, because the protocol will never change, but it would be slightly cleaner to have a constant.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/66)
> Add public constant for header size

- .github/workflows/ci.yml
- Cargo.toml
- src/bin/tcp2udp.rs
- src/forward_traffic.rs
- src/lib.rs
In Rust 1.82 we finally get to omit impossible branches in pattern matching: https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html#omitting-empty-types-in-pattern-matching
This PR utilize that in order to get rid of the custom `NeverOkResult` trait.
This is not an important change, nor is it a high priority. We might want to wait with merging this until we use Rust 1.82 in the main repo. Just so we don't block ourselves from upgrading to the latest `udp-over-tcp` in case we need it. I just realized this potential cleanup and wanted to submit a PR while I had it on the top of my mind :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/udp-over-tcp/69)
> Remove custom NeverOkResult trait and instead use new Rust 1.82 matching
